### ISSUE TITLE
Dynamic classes are not generated

### ISSUE THREAD

**Issue by JPOstholt** [conver-unocss/animated-unocss#34]
When I use either method to dynamically generate delay classes shown below, the corresponding classes are not in the output.

**My code:**

```vue
<p
  v-for="item, index in items"
  :class="[`animate-delay-[${index * 100}ms]`]"
  :animated="`~ fade-in-down delay-${index * 100}`"
>
  {{ item }}
</p>
``` 

**Expectation:**
The delay classes are generated and the animations stagger

Btw thanks for doing this package :) I otherwise love it

**Comment by elonehoo** [comment]
Ah ha, maybe you need to give me some time for me to try and solve it.

**Comment by elonehoo** [comment]
Hey @JPOstholt  , can you try the latest version, it should work
